[package]
name = "incubait"
version = "0.1.0"
edition = "2024"

[lib]
name = "incubait"        # the Rust-side name of the library
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
bytemuck = "1.23.1"
rkyv = "0.8.11"
tracing = "0.1.41"